version: "3.9"
services:
  db:
    image: postgres:15-alpine
    container_name: ${PROJECT_NAME}_${ENV}_db
    restart: unless-stopped
    networks:
      - network
    ports:
      - 127.0.0.1:${DB_PORT}:5432
    volumes:
      - db:/var/lib/postgresql/dataservice
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: datapimp
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "app" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  mq:
    image: rabbitmq:3-management
    container_name: ${PROJECT_NAME}_${ENV}_mq
    restart: unless-stopped
    networks:
      - network
    ports:
      - 127.0.0.1:${MQ_PORT_1}:5672
      - 127.0.0.1:${MQ_PORT_2}:15672
    volumes:
      - mq:/var/lib/rabbitmq/
      - ./log/mq:/var/log/rabbitmq
    environment:
      RABBITMQ_DEFAULT_VHOST: datapimp

volumes:
  db:
    name: ${PROJECT_NAME}_${ENV}_db
  mq:
    name: ${PROJECT_NAME}_${ENV}_mq

networks:
  network:
    name: ${PROJECT_NAME}_${ENV}
    driver: bridge
