version: '3'

includes:
  app:
    taskfile: .ci/Taskfile.app.yaml
    optional: true
  gen:
    taskfile: .ci/Taskfile.gen.yaml
    optional: true
  lint:
    taskfile: .ci/Taskfile.lint.yaml
    optional: true
  test:
    taskfile: .ci/Taskfile.test.yaml
    optional: true
  build:
    taskfile: .ci/Taskfile.build.yaml
    optional: true

tasks:
 init:
   desc: Initialize environment
   cmds:
     - rm -rf .ci
     - git clone https://github.com/ashep/go-ci.git .ci
