version: '3'

vars:
  APP_NAME:
    sh: basename $(pwd)
  APP_VERSION:
    sh: git rev-parse --abbrev-ref HEAD
  ARCH:
    sh: uname -m
  REGISTRY_REPO: ashep/{{.APP_NAME}}

includes:
  app:
    taskfile: .ci/Taskfile.app.yaml
    optional: true
  gen:
    taskfile: .ci/Taskfile.gen.yaml
    optional: true
  lint:
    taskfile: .ci/Taskfile.lint.yaml
    optional: true
  test:
    taskfile: .ci/Taskfile.test.yaml
    optional: true
  docker:
    taskfile: .ci/Taskfile.docker.yaml
    optional: true

tasks:
  init:
    desc: Initialize environment
    cmds:
      - rm -rf .ci
      - git clone https://github.com/ashep/go-ci.git .ci
