name: Prepare
description: Installs and setups all necessary binaries
runs:
  using: composite
  steps:
    - uses: arduino/setup-task@v1
    - uses: actions/setup-go@v4
      with:
        cache: false
        go-version-file: go.mod
