name: build
on: push
jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: ashep/go-ci/actions/prepare@main
      - run: task lint:golangci

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: ashep/go-ci/actions/prepare@main
      - run: task test:unit

  func-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: ashep/go-ci/actions/prepare@main
      - run: task test:func

  build:
    runs-on: ubuntu-latest
    needs:
      - unit-tests
      - func-tests
    env:
      TASK_APP_NAME: ${{ github.event.repository.name }}
      TASK_APP_VERSION: ${{ github.ref_name }}
    steps:
      - uses: ashep/go-ci/actions/prepare@main
      - run: task docker:build

  publish:
    runs-on: ubuntu-latest
    needs:
      - build
    env:
      TASK_APP_NAME: ${{ github.event.repository.name }}
      TASK_APP_VERSION: ${{ github.ref_name }}
    steps:
      - uses: ashep/go-ci-github/actions/prepare@main
      - run: docker login -u ${{ vars.REGISTRY_USER }} -p ${{ secrets.REGISTRY_PASSWD }}
      - run: task docker:push
