name: build
on: push
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: ashep/go-ci-github/actions/prepare
      - run: task lint

  test:
    name: Test
    runs-on: ubuntu-latest
    needs:
      - lint
    steps:
      - uses: ashep/go-ci-github/actions/prepare
      - run: go mod vendor
      - run: task test.unit
      - run: task test.func

  build:
    name: Build
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - uses: ashep/go-ci-github/actions/prepare
      - run: docker login -u ${{ vars.REGISTRY_USER }} -p ${{ secrets.REGISTRY_PASSWD }}
      - run: docker build --build-arg ARCH=x86_64 --build-arg APP_NAME=${{ github.event.repository.name }} --build-arg APP_VERSION=${{ github.ref_name }} -t ${{ github.event.repository.name }} .
      - if: github.ref_name != 'main'
        run: |
          docker tag ${{ github.event.repository.name }} ${{ vars.REGISTRY_USER }}/${{ github.event.repository.name }}:dev
          docker push ${{ vars.REGISTRY_USER }}/${{ github.event.repository.name }}:dev
      - if: github.ref_name == 'main'
        run: |
          docker tag ${{ github.event.repository.name }} ${{ vars.REGISTRY_USER }}/${{ github.event.repository.name }}:latest
          docker push ${{ vars.REGISTRY_USER }}/${{ github.event.repository.name }}:latest
