on: push
jobs:
  lint:
    uses: ashep/ci/.github/workflows/go-lint.yaml@v1
    with:
      govulncheck_enabled: false # temporary due to a bug https://github.com/golang/go/issues/66139

  test:
    needs:
      - lint
    uses: ashep/ci/.github/workflows/go-test.yaml@v1

  build:
    needs:
      - test
    uses: ashep/ci/.github/workflows/go-build.yaml@v1
    with:
      registry_user: ${{ vars.REGISTRY_USER }}
    secrets:
      registry_password: ${{ secrets.REGISTRY_PASSWORD }}
