name: tests
on: push
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Install dependencies
        run: go mod vendor

      - name: Test
        run: go test -v ./...

  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker login
        run: docker login -u ${{ secrets.REGISTRY_USER }} -p ${{ secrets.REGISTRY_PASSWD }}

      - name: Build
        run: docker build --build-arg ARCH=x86_64 --build-arg APP_NAME=${{ github.event.repository.name }} --build-arg APP_VERSION=${{ github.ref_name }} -t ${{ github.event.repository.name }} .

      - name: Push ref
        if: github.ref_name != 'main'
        run: |
          docker tag ${{ github.event.repository.name }} ${{ secrets.REGISTRY_USER }}/${{ github.event.repository.name }}:${{ github.ref_name }}
          docker push ${{ secrets.REGISTRY_USER }}/${{ github.event.repository.name }}:${{ github.ref_name }}

      - name: Push latest
        if: github.ref_name == 'main'
        run: |
          docker tag ${{ github.event.repository.name }} ${{ secrets.REGISTRY_USER }}/${{ github.event.repository.name }}:latest
          docker push ${{ secrets.REGISTRY_USER }}/${{ github.event.repository.name }}:latest
